### ISSUE TITLE
On supporting unaligned/unmapped reads

### ISSUE THREAD

**Issue by wangbingqiang** [hammerlab/spark-bam#18]
First of all, Spark-BAM is awesome work.  We are excited when looking at it, and decided to employ it in one ongoing project.

However, most (if not all) of our data are directly converted fastq files (to bam), which are not aligned or mapped at all.  I am wondering if Spark-BAM works well under such a scenario, for both Illumina short and PacBio long reads.

**Comment by ryan-williams** [comment]
Thanks!

AFAIK, it will work fine on unaligned reads! There were many unaligned reads in [the BAMs that I benchmarked on](http://www.hammerlab.org/spark-bam/benchmarks#data), and I don't think anything would work notably differently if the BAM was all unaligned reads. If you find otherwise, please follow up here!
